### ISSUE TITLE
non va il comando

### ISSUE THREAD

**Issue by TyroneFromJail** [MattiaBLX/AdvTGBot#10]
if ($TGBot->text == '/start') {
  $TGBot->sendMessage($TGBot->chat_id, "funziona");
}

**Comment by MattiaBLX** [comment]
@TyroneFromJail Ciao Tyrone, ti chiediamo di specificare le specifiche del tuo host, come hai settato il webhook e qualsiasi altro dettagli che ritieni importante. 

Attendiamo una risposta.

**Comment by TyroneFromJail** [comment]
il webhook l'ho settato come scritto nel github cioè cosi https://api.telegram.org/bot{TOKEN}/setwebhook?url=https://{DOMAIN}/{DIRECTORY}?fpam={KEY}%26token={TOKEN}

**Comment by giovanniacanforah** [comment]
@TyroneFromJail Potresti per favore inviare il token del bot in privata a @MattiaBLX su telegram?

**Comment by MattiaBLX** [comment]
@TyroneFromJail Ok, assicurati che il webhook sia ben settato effettuando la seguente richiesta: https://api.telegram.org/botTOKEN/getwebhookinfo e vedi se tutto corrisponde a come dovrebbe essere, se non sei sicuro, invia il risultato censurando token ed fpam.

**Comment by TyroneFromJail** [comment]
ok c'è l'fpam ma non &token= ecc

**Comment by MattiaBLX** [comment]
@TyroneFromJail Allora prova riconfigurare il webhook, seguendo per bene la guida e sostituendo solo quello che ti viene chiesto.

**Comment by TyroneFromJail** [comment]
ok provo

**Comment by TyroneFromJail** [comment]
Wrong response from the webhook: 301 Moved Permanently
ora mi da questo

**Comment by MattiaBLX** [comment]
@TyroneFromJail Molto probabilmente non hai messo index.php nel webhook, prova a settarlo in quel modo.

**Comment by TyroneFromJail** [comment]
ora va grazie mille @MattiaBLX
