### ISSUE TITLE
Fatal error: Call to a member function settings() on null in /membri/nomehost/nomecartella/conf.php on line 5

### ISSUE THREAD

**Issue by mamo5900** [MattiaBLX/AdvTGBot#11]
ho questo problema che causa il malfunzionamento del bot

**Comment by MattiaBLX** [comment]
@mamo5900 Questo non è il problema che causa il non funzionamento del tuo bot. Il file conf.php non deve essere aperto perchè è studiato per essere richiamato da index.php.

**Comment by mamo5900** [comment]
non viene richiamato se esiste un fatal error
