### ISSUE TITLE
E' possibile far inviare al bot determinate immagini all'esecuzione un comando?

### ISSUE THREAD

**Issue by mamo5900** [MattiaBLX/AdvTGBot#12]
E' possibile far inviare al bot determinate immagini all'esecuzione un comando? Sarebbe utile al fine del mio scopo

**Comment by MattiaBLX** [comment]
@mamo5900 Ciao. 
Gli issue su github servono per eventuali "mal funzionamenti" di AdvTGBot, non su come usarlo, siccome ti basterebbe leggere TGBot.php. 
Sei pregato di non creare più issue del genere, grazie mille.

**Comment by mamo5900** [comment]
l'ho chiesto perché il sendPhoto non mi funziona, non invia l'immagine

**Comment by MattiaBLX** [comment]
Allora, invece di fare un issue stupido, sei pregato di postare i procedimenti che hai fatto (in un altro issue) con codice e tutto cioè che ritieni utile.
