### ISSUE TITLE
problema col sendPhoto()

### ISSUE THREAD

**Issue by mamo5900** [MattiaBLX/AdvTGBot#13]
Ho caricato l'immagine nella cartella del bot e sul file commands.php , dopo aver definito il comando, ho digitato il seguente pezzo di codice:
	$TGBot->sendPhoto($TGBot->chat_id, "image.png");

Ma il bot non invia la suddetta immagine

**Comment by MattiaBLX** [comment]
@mamo5900 Come si legge nel codice, il file upload non è ancora supportato.

**Comment by davtur19** [comment]
@MattiaBLX .
