### ISSUE TITLE
Non riesco ad aggiungere la tastiera inline

### ISSUE THREAD

**Issue by Zamassss** [MattiaBLX/AdvTGBot#14]
Ho inserito questo pezzo di codice ma niente, la tastiera non esce
if($TGBot->text=='Canalli'){
$keyboard = [
    ["inline", "inline2"],
    ["Pulsante2", "Pulsante3"],
];
$key = array(
"resize_keyboard" => true,
"keyboard" => $keyboard,
);
   keyboard($key, "Ecco a te la lista dei canali, $cid");
   }
if($TGBot ->text=='Canali op'){
	$but = array(array(array("text" => "Gruppo principale", "url" => "www.google.com"),),);
	inlinekeyboard($but, $cid, "Clicca su questo pulsante per entrare nel gruppo principale");
	}

**Comment by V1rusFalcon** [comment]
@Zamassss Ma, scusa... dove l'hai trovato inlinekeyboard();?

**Comment by MattiaBLX** [comment]
Almeno impariamo a leggere il codice di AdvTGBot e a programmare, altrimenti facciamo ste porcate.
