### ISSUE TITLE
Problema Dopo la procedura di installazione

### ISSUE THREAD

**Issue by franck86** [MattiaBLX/AdvTGBot#15]
Salve.
Chiedo supporto in quanto dopo la procedura di installazione effettuata seguendo la video guida non ricevo alcuna risposta dal mio bot.
Il webhook viene settato come richiesto; tuttavia effettuando la chiamata allapi getwebookinfo ricevo questa risposta :

{"ok":true,"result":{"url":"https://livehost.altervista.org/LiveHostBot/index.php?fpam=aE361cJmXFINL2r526HFpKGWnYizDHgkVdBCAl&token=79742305:AAF8OvSi2Gus67hBXkdmTfWWbHTI97dTI","has_custom_certificate":false,"pending_update_count":33,"last_error_date":1556208786,"last_error_message":"Wrong response from the webhook: 301 Moved Permanently","max_connections":40}}

Grazie in anticipo

**Comment by MattiaBLX** [comment]
@franck86 Elimina il post. Hai lasciato visibile il token.

**Comment by franck86** [comment]
Tranquillo è sbagliato ;)

**Comment by MattiaBLX** [comment]
@franck86 Ok comunque, puoi mandarmi la tua index.php?

**Comment by franck86** [comment]
Certo te la invio tra poco.
Cmq se può esserti di aiuto chiamando puntualmente la index.php passandogli i 2 parametri appropriati la pagina risponde status ok anche per mysql, infatti crea anche la tabella

**Comment by franck86** [comment]
Questa la mia index.php
ps la key di advTGBot è alterata.

<?php
/*This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.*/

include 'TGBot.php';
$TGBot = new TGBot(file_get_contents('php://input'), 'aE6McJmXFIXXXXXXXo89pKGWnYizDHgkVdBCAl', $_GET['fpam'], $_GET['token']);
$TGBot->SecTest();
include 'conf.php';
include 'mysql.php';
include 'postgres.php';
include 'commands.php';

**Comment by franck86** [comment]
Questa la risposta se chiamo la pagina index.php passando token ed fpam corretti

![test](https://user-images.githubusercontent.com/8684910/56755007-c2a32700-678e-11e9-8a3d-7db347b9c6fe.PNG)

**Comment by MattiaBLX** [comment]
@franck86 Ok perfetto. 
Fai una cosa, richiama dalle api di telegram deleteWebhook e risettalo

**Comment by franck86** [comment]
Certo. Riprovo anche se lho fatto diverse volte prima di disturbare.
Ti aggiorno

**Comment by franck86** [comment]
Niente, ho provato anche a revocare il token del bot e a creare webhook nuovo ma nulla sempre solito problema come da immagine seguente 

![image](https://user-images.githubusercontent.com/8684910/56758406-df435d00-6796-11e9-929d-52be1a082740.png)

Possibile che il motivo sia questo?

![image](https://user-images.githubusercontent.com/8684910/56758319-a0150c00-6796-11e9-89a7-4c6c5036cd28.png)

**Comment by franck86** [comment]
Ho notato un'altra cosa (non so se puo essere utile) : quando richiamo la index.php del sito con protocollo https la richiesta viene forwardata verso protocollo http. Non so se puo essere un problema per il corretto funizionamento; nel caso mi manca qualche tipo di configurazione su altervista?

**Comment by MattiaBLX** [comment]
@franck86 Esatto, il problema è questo allora. Abilita HTTPs e Cloudflare.

**Comment by Pato05** [comment]
@MattiaBLX Lol

**Comment by franck86** [comment]
![image](https://user-images.githubusercontent.com/8684910/56758919-00f11400-6798-11e9-9690-d5214c24da82.png)

**Comment by franck86** [comment]
I servizi sono correttamente Attivati. Almeno da quello che sembra.

**Comment by MattiaBLX** [comment]
@franck86 Stranissimo allora

**Comment by MattiaBLX** [comment]
@MattiaBLX Contatta AV

**Comment by franck86** [comment]
Si contatto il supporto.
Mi manca qualche tipo di configurazione su Altervista secondo la tua esperienza?

**Comment by MattiaBLX** [comment]
@franck86 Non mi sembra

**Comment by franck86** [comment]
Grazie mille per il momento. 
Ti aggiorno.

**Comment by MattiaBLX** [comment]
@franck86 Kk, aspetto tuo notizie.

**Comment by franck86** [comment]
Ok, sembra che ho risolto e funziona perfettamente.
Scrivo qui la soluzione nella speranza possa essere di aiuto a qualcuno.
Sembra che oltre ad attivare https e claudflare per fare in modo che il dominio elabori poi richieste effettivamente in https ci sia bisogno di una modifica al file .htaccess aggiungendo queste 3 righe di script al suo interno :

RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteCond %{HTTPS} off
RewriteRule .* https://nome.altervista.org%{REQUEST_URI} [L,R=301]

Fare attenzione, nel caso gia esistessero di sostituirle e non di aggiungerle.

Grazie ancora del supporto e del lavoro che fai.

Saluti

**Comment by MattiaBLX** [comment]
@franck86 Grazie mille per averci dato quest'informazione.
