### ISSUE TITLE
Cascata di bottoni inline

### ISSUE THREAD

**Issue by XDiamond7D7** [MattiaBLX/AdvTGBot#16]
Ho creato un comando che dovrebbe "inviare" nel gruppo un menu per fare delle determinate cose con  i bottoni... L'unico problema è che quando clicco un qualsiasi bottone si apre una cascata di bottoni (di altri menù) e scusate per la ripetizione

**Comment by MattiaBLX** [comment]
@XDiamond7D7

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Puoi inviare degli screenshot?

**Comment by XDiamond7D7** [comment]
@MattiaBLX SI

**Comment by XDiamond7D7** [comment]
@XDiamond7D7

**Comment by XDiamond7D7** [comment]
@XDiamond7D7 Dopo qualche secondo si modifica il messaggio

**Comment by XDiamond7D7** [comment]
![GitHawk Upload by XDiamond7D7](https://i.imgur.com/iysYOPx.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Il problema non dipende da AdvTGBot ma dal tuo codice.

**Comment by XDiamond7D7** [comment]
@MattiaBLX Rip allora... È tutto giusto
