### ISSUE TITLE
Problema con il bot: Security test: not passed, script killed.

### ISSUE THREAD

**Issue by Nikotecnology05** [MattiaBLX/AdvTGBot#17]
Ho seguito il tutorial su youtube ma quando apro l'index.php da questo errore: Security test: not passed, script killed.

**Comment by MattiaBLX** [comment]
Lo script per eseguirsi senza errori, necessita che tu gli fornisca i parametri get FPAM e il TOKEN come puoi vedere nell'index.

**Comment by Nikotecnology05** [comment]
@MattiaBLX questo

**Comment by Nikotecnology05** [comment]
@Nikotecnology05 Parse error: syntax error, unexpected '}', expecting ',' or ')' in /membri/nikotecnology/botn2/AdvTGBot-master/commands.php on line 6

**Comment by Nikotecnology05** [comment]
@Nikotecnology05 continua a non andare

**Comment by MattiaBLX** [comment]
Questo perchè non sai programmare. È evidente l'errore di sintassi, e advtgbot richiede un minimo di conoscenza di php.
