### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by Andreullo10** [MattiaBLX/AdvTGBot#18]
non riesco ad attivare la webhook

**Comment by V1rusFalcon** [comment]
@Andreullo10 Se non ci dai più informazioni non riusciamo ad aiutarti

**Comment by vpervenditti** [comment]
@Andreullo10 LA WEBHOOK

**Comment by Andreullo10** [comment]
adesso ho risolto il webhook ma non va il bot

**Comment by vpervenditti** [comment]
@vpervenditti cos

**Comment by vpervenditti** [comment]
@vpervenditti Sesso anal

**Comment by vpervenditti** [comment]
@vpervenditti Mai pensato che il problema non è il webhook, ma tu?

**Comment by MattiaBLX** [comment]
Potrei sembrare scortese, ma, quando riuscirai a fare un issue decente potremmo aiutarti.

**Comment by V1rusFalcon** [comment]
Rileggi il mio commento.

**Comment by V1rusFalcon** [comment]
@vpervenditti .del
