### ISSUE TITLE
non va il comando 

### ISSUE THREAD

**Issue by Andreullo10** [MattiaBLX/AdvTGBot#19]
già ho settato la webhook con l'url che ho trovato su GitHub, ho scritto anche il codice in commands,php:
if ($TGBot->text == '/start') {
$TGBot->sendMessage($TGBot->chat_id, "funziona");
}
ma appena provo sul bot non funziona

**Comment by MattiaBLX** [comment]
@Andreullo10 Per aiutarti, sei pregato di fornire più dettagli.

**Comment by Andreullo10** [comment]
quali?

**Comment by Andreullo10** [comment]
quando ho settato la webhook è uscito questo: {"ok":true,"result":true,"description":"Webhook was set"}

**Comment by MattiaBLX** [comment]
@Andreullo10 Non basta, possiamo avere il risultato di getwebhookinfo?

**Comment by Andreullo10** [comment]
@MattiaBLX {"ok":true,"result":{"url":"https://communitytalia.altervista.org/MultiItalia_ItaliaBot/index.php?fpam=lXUDoOu6cahC0n8q51KzmSbHFfZ3eWMkVrA7EgiQ26token=819971842:AAGISjjZS6BrLc8rTk96opjF-o-tlA9qpGU","has_custom_certificate":false,"pending_update_count":25,"last_error_date":1557065568,"last_error_message":"Wrong response from the webhook: 301 Moved Permanently","max_connections":40}}

**Comment by MattiaBLX** [comment]
@Andreullo10 Prima di tutto, avresti dovuto censurare il token, secondo, hai scritto 26 e non %26. Risetta il webhook

**Comment by Andreullo10** [comment]
ah ok

**Comment by Andreullo10** [comment]
fatto ora?

**Comment by MattiaBLX** [comment]
@Andreullo10 Ora vedi se funziona .-.

**Comment by Andreullo10** [comment]
provato ma nulla

**Comment by MattiaBLX** [comment]
@Andreullo10 Risultato di getwebhookinfo?

**Comment by Andreullo10** [comment]
{"ok":true,"result":{"url":"https://communitytalia.altervista.org/MultiItalia_ItaliaBot/index.php?fpam=lXUDoOu6cahC0n8q51KzmSbHFfZ3eWMkVrA7EgiQ&token={TOKEN}","has_custom_certificate":false,"pending_update_count":2,"last_error_date":1557066252,"last_error_message":"Wrong response from the webhook: 301 Moved Permanently","max_connections":40}}

**Comment by MattiaBLX** [comment]
@Andreullo10 Se apri quel link cosa dice?

**Comment by Andreullo10** [comment]
Security test: OK.

**Comment by MattiaBLX** [comment]
@Andreullo10 Ok, allora

deletewebhook
Setwebhook di nuovo

**Comment by Andreullo10** [comment]
fatto provo?

**Comment by MattiaBLX** [comment]
@Andreullo10 Si 😐

**Comment by Andreullo10** [comment]
nulla 😐

**Comment by MattiaBLX** [comment]
@Andreullo10 Https è attivo?

**Comment by Andreullo10** [comment]
si

**Comment by MattiaBLX** [comment]
@Andreullo10 Non loè

**Comment by Andreullo10** [comment]
![HTTPS](https://user-images.githubusercontent.com/50278227/57195621-1400a280-6f55-11e9-8087-8287354978f3.png)

**Comment by MattiaBLX** [comment]
@Andreullo10 Allora è un problema di altervista, siccome l'https redirecta su http
