### ISSUE TITLE
Explode in  php7

### ISSUE THREAD

**Issue by R0xxi0** [MattiaBLX/AdvTGBot#20]
if ($TGBot->text == "prova"){
    $t = explode(' ', $TGBot->text);
    $TGBot->sendMessage($TGBot->chat_id, "aggiunto".$t[1]."alla prova");
}

con questo comando la risposta avviene solo se non faccio funzionare l'explode ovvero scrivendo solo (in questo caso) "prova"

**Comment by MattiaBLX** [comment]
@R0xxi0 == serve per verificare se la stringa A è uguale a stringa B, quello che vuoi fare tu devi farlo con php.net/strpos.
