### ISSUE TITLE
Query nel global post errate mysql.php

### ISSUE THREAD

**Issue by mamo5900** [MattiaBLX/AdvTGBot#21]
Col vostro sistema di query ( "SELECT * FROM […] ") vengono presi tutti i record inclusi i duplicati. Se un utente ha fatto 1000 chiamate sul bot verrà registrato giustamente 1000 volte e col global post riceverà altrettante volte il post. Consiglio di sostituire la query con "SELECT DISTINCT chat_id  FROM […] " per evitare i duplicati

**Comment by MattiaBLX** [comment]
Assolutamente errato. Quando l'utente invia un update al bot, se nel database non è presente, viene inserito, altiementi, viene fatto un UPDATE, quindi non ci sono duplicati. https://github.com/MattiaBLX/AdvTGBot/blob/94ed7a3d7ea53c2f4815a9736ef68836315df641/mysql.php#L27

**Comment by mamo5900** [comment]
ci sono eccome, non ho toccato nulla e vengono duplicati

**Comment by MattiaBLX** [comment]
Invia uno screen

**Comment by mamo5900** [comment]
![photo_2019-05-11_18-54-55](https://user-images.githubusercontent.com/49442504/57572694-58d97d00-741e-11e9-8834-08ce73445b03.jpg)

**Comment by MattiaBLX** [comment]
@mamo5900 Potrebbe essere un bug di phpmyadmin... Puoi eseguire la query da cli?

**Comment by MattiaBLX** [comment]
Mistero risolto sul gruppo... l'autore del issue ha erroneamente cancellato una parte della query.
