### ISSUE TITLE
Non funziona una cosa..

### ISSUE THREAD

**Issue by XDiamond7D7** [MattiaBLX/AdvTGBot#22]
$TGBot->mdb->query("DELETE  FROM chat WHERE chat_id = $del");

$del sarebbe la variabile del nome della riga da eliminare

Però non funziona...

**Comment by MattiaBLX** [comment]
Prima di tutto, metti nomi decenti agli issue. E vorrei ricordarti che il supporto fornisce aiuto per AdvTGBot, non per MySQL e come utilizzarlo. Inoltre, non è il modo corretto di utilizzare PDO.

**Comment by XDiamond7D7** [comment]
@MattiaBLX Va bene scusatemi

**Comment by Knocks83** [comment]
@XDiamond7D7 Lol
