### ISSUE TITLE
Non funziona sendVideo

### ISSUE THREAD

**Issue by roci33** [MattiaBLX/AdvTGBot#25]
Non funziona sendVideo, non da errori, ma non manda il video; uso il seguente codice:

if($TGBot->text == "/video"){
$TGBot->sendVideo($TGBot->chat_id, "mosconi1.mp4");
}

**Comment by MattiaBLX** [comment]
@roci33 File upload non supportato

**Comment by roci33** [comment]
Quindi non si può sistemare?
