### ISSUE TITLE
Errore all'esecuzione dell'index.php

### ISSUE THREAD

**Issue by smsbxksi** [MattiaBLX/AdvTGBot#27]
All'esecuzione dell'index ottengo questo risultato:
Security test: not passed, script killed.
Questo il mio index.php:
<?php
/*This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.*/

include 'TGBot.php';
$TGBot = new TGBot(file_get_contents('php://input'), 'd*******zMFL', $_GET['d*******zMFL'], $_GET['3******0gixIoI']);
$TGBot->SecTest();
include 'conf.php';
include 'mysql.php';
include 'postgres.php';
include 'commands.php';

**Comment by giovanniacanforah** [comment]
@smsbxksi Hai per caso tolto qualche riga dall'index.php?

**Comment by smsbxksi** [comment]
no, lo riallego qui:
<?php
/*This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.*/

include 'TGBot.php';
$TGBot = new TGBot(file_get_contents('php://input'), 'dNDnpgi5ac2**1zMFL', $_GET['dNDnpgi5ac2AGw0**o**fHlrCWEh4Ix***FL'], $_GET['37161737**Nq0gixIoI']);
$TGBot->SecTest();
include 'conf.php';
include 'mysql.php';
include 'postgres.php';
include 'commands.php';

**Comment by giovanniacanforah** [comment]
@smsbxksi dove sta $_GET['fpam'] e $_GET['token'] deve rimanere così, devi modificaresolo FPAM dove sta tutto maiuscolo

**Comment by smsbxksi** [comment]
sì, è quello che ho fatto, non mi copia tutto il codice

**Comment by giovanniacanforah** [comment]
@smsbxksi no, lo hai modificato, per favore copia di nuovo il codice di https://raw.githubusercontent.com/MattiaBLX/AdvTGBot/master/index.php e modifica solo FPAM dove sta tutto maiuscolo, il resto non fare nulla.

**Comment by smsbxksi** [comment]
![Cattura](https://user-images.githubusercontent.com/28309041/58751487-66bf7280-849f-11e9-80ba-d9ea9c9f9326.PNG)

**Comment by giovanniacanforah** [comment]
Ok, se hai scritto così, allora il codice proprio è corretto. Sicuro di aver impostato bene il webhook del token?

**Comment by smsbxksi** [comment]
sì, ho usato questo link:
https://api.telegram.org/bot371*****gixIoI/setwebhook?url=https://emulationworld.altervista.org/emulation/index.php?fpam=dND****Ix1zMFL%26token=371****0gixIoI

**Comment by giovanniacanforah** [comment]
il token è giusto?

**Comment by smsbxksi** [comment]
sì

**Comment by MattiaBLX** [comment]
Duplicate of #17

**Comment by MattiaBLX** [comment]
Quando esegui l'index devi passare anche i parametri token ed fpam.

**Comment by smsbxksi** [comment]
ok, provo

**Comment by smsbxksi** [comment]
stesso errore

**Comment by MattiaBLX** [comment]
Fammi vedere come faicla la richiesta, ovviamente censura i dati

**Comment by smsbxksi** [comment]
![Cattura](https://user-images.githubusercontent.com/28309041/58751597-d3873c80-84a0-11e9-8453-57e1796a3497.PNG)

**Comment by MattiaBLX** [comment]
:facepalm:

**Comment by smsbxksi** [comment]
https://api.telegram.org/bot371617*****IoI/setwebhook?url=https://emulationworld.altervista.org/emulation/index.php?fpam=dN*****WEh4Ix1zMFL%26token=37***gixIoI

**Comment by MattiaBLX** [comment]
Non ti ho detto di modificare le variabili GET, ma di passare i valori quando fai la richiesta

**Comment by smsbxksi** [comment]
ah ok

**Comment by smsbxksi** [comment]
chiedo scusa, non mi era chiaro questo passaggio, ho
