### ISSUE TITLE
Problema con bottoni

### ISSUE THREAD

**Issue by R0xxi0** [MattiaBLX/AdvTGBot#32]
ho creato uno script per un bot molto complesso e per gli utenti ho scelto di creare un menù con dei bottoni non avevo internet e ho continuato a programmare e tutto il fine settimane oggi uploado sul ftp e niente funzio ma il calback no ovvero il comando funzioa i bottoni si vedono ma se gli schiaccio carica e poi non succede nulla 

ecco un esempio ultra semplificato dello script con i bottoni

if (strpos($TGBot->text, "/comando")!== false){
  $bottoni[] = [
  [
  "text" => "bottone1",
  "callback_data" => "clb1",
  ],
  [
  "text" => "bottone2",
  "callback_data" => "clb2",
  ],
  ];
    $TGBot->sendMessage($TGBot->chat_id, "testo a caso", $bottoni);
}

if ($TGBot->cbdata_text == "cbl1"){
  $TGBot->editMessage($TGBot->chat_id, $TGBot->message_id, "testo a caso pt.2");
}

if ($TGBot->cbdata_text == "cbl3"){
  $TGBot->editMessage($TGBot->chat_id, $TGBot->message_id, "testo a caso pt.3");
}

**Comment by giovanniacanforah** [comment]
@R0xxi0 Si tratta di un errore di scrittura. Nello start hai messo CLB1 e CLB2, nei tasti hai messo CBL1 e CBL2.
