### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by FraPlusPlus** [MattiaBLX/AdvTGBot#33]
mattia, questo script non funziona, mi ha aiutato anche LordGork ma non vuole funzionare:

if($TGBot->text == "id"){
$TGBot->sendMessage($TGBot->chat_id, $user_id);
}

ho anche ricreato la variabile $user_id ma niente da fare.

**Comment by giovanniacanforah** [comment]
@FraPlusPlus Non esiste $user_id. Solo $TGBot->user_id

**Comment by FraPlusPlus** [comment]
@giovanniacanforah eh sì ma per mettere nel sendMessage per far mandare l'id dell'utente cosa ci metto?

**Comment by Knocks83** [comment]
if($TGBot->text == "id"){
$TGBot->sendMessage($TGBot->chat_id, $TGBot->user_id);
}

**Comment by FraPlusPlus** [comment]
@Knocks83 grazie, ma non si potrebbe creare la variabile $user_id e farla funzionare?

**Comment by Knocks83** [comment]
$user_id = $TGBot->user_id;

**Comment by dododhn** [comment]
@FraPlusPlus $user_id = $TGBot-user_id;
Ma non ha senso

**Comment by giovanniacanforah** [comment]
@dododhn Purtroppo originariamente è fatta a classi.
Noi sconsigliamo, peró, se proprio si vuole si dichiarano variabili alternative.
