### ISSUE TITLE
Problemi con il curl

### ISSUE THREAD

**Issue by XDiamond7D7** [MattiaBLX/AdvTGBot#6]
**Inserisci tutto quello che può aiutarci a risolvere il problema.**
Ho installato curl e curl-php:

Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/bot/CartellaBot/TGBot.php:13 Stack trace: #0 /var/www/html/bot/CartellaBot/index.php(7): TGBot->__construct('', 'FPAM KEY...', NULL, NULL) #1 {main} thrown in /var/www/html/bot/CartellaBot/TGBot.php on line 13

Ho anche riavviato apache

**Comment by MattiaBLX** [comment]
Mhh. Puoi fare php -v?

**Comment by XDiamond7D7** [comment]
PHP 7.2.16-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by Invy55** [comment]
apache colpisce ancora

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Ok, apt install php7.2-curl curl

**Comment by XDiamond7D7** [comment]
Fatto, riavvio?

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Sì

**Comment by XDiamond7D7** [comment]
C'è ancora il problema

**Comment by XDiamond7D7** [comment]
Posso provare a resettare il vps e reinstallare tutto...

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Assolutamente no. Ora vediamo cosa fare dammi un secondo.

**Comment by MattiaBLX** [comment]
@MattiaBLX ls /etc/php/ puoi darmi il risultato?

**Comment by XDiamond7D7** [comment]
Ah... 7.2  7.3

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Ok, hai due versioni di PHP.
Quale sta usando Apache?

**Comment by XDiamond7D7** [comment]
Come faccio a vederlo?

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Crea un file php e richiama la funzione phpinfo()

**Comment by XDiamond7D7** [comment]
Sto usando la 7.2

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Ok.
Apt purge php7.3* --remove

**Comment by XDiamond7D7** [comment]
Fatto

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Va?

**Comment by XDiamond7D7** [comment]
No

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Ok. Allora reinstalla php, php curl ecc. 
Possibilmente disinstallando quella attuale e seguendo una guida affidabile

**Comment by XDiamond7D7** [comment]
Ok ci provo, grazie!

**Comment by V1rusFalcon** [comment]
@XDiamond7D7 Se il problema persiste manda ciò che riporta il config di apache

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Problema risolto?

**Comment by XDiamond7D7** [comment]
Forse ho risolto, però adesso succede questo: (index.php)

Security test: not passed, script killed.

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Ok hai risolto.
La soluzione a questo problema però è logica.

**Comment by XDiamond7D7** [comment]
@MattiaBLX Va bene grazie per avermi aiutato!
