### ISSUE TITLE
Ho un problema con l'index

### ISSUE THREAD

**Issue by XDiamond7D7** [MattiaBLX/AdvTGBot#7]
Con il seguente link: dominio/bot/BlockProtecterBot/index.php

Mi spunta:

<?php
/*This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.*/

include 'TGBot.php';
$TGBot = new TGBot(file_get_contents('php://input'), 'KEY', $_GET['fpam'], $_GET['token']);
$TGBot->SecTest();
include 'conf.php';
include 'mysql.php';
include 'postgres.php';
include 'commands.php';

E il bot non funziona. Adesso non capisco se ho dimenticato ad installare qualcosa, ma ho installato:
Il certificato SSL
Curl /php curl
Php7.3

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Il tuo webserver non sta eseguendo PHP

**Comment by V1rusFalcon** [comment]
@XDiamond7D7 Che programma usi per il webserver?

**Comment by XDiamond7D7** [comment]
programma in che senso? Tipo Ubuntu?

**Comment by V1rusFalcon** [comment]
@XDiamond7D7 Apache, nginx, httpd o altro

**Comment by XDiamond7D7** [comment]
Ah scusa. Comunque Apache

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Quella è la tua distro.
Non sai neanche le basi, perchè hai comprato un server?

**Comment by V1rusFalcon** [comment]
@XDiamond7D7 Manda il config di apache

**Comment by XDiamond7D7** [comment]
@MattiaBLX Perchè non voglio hostare bot su altervista

**Comment by MattiaBLX** [comment]
@XDiamond7D7 Ok. Compra un webhost, no?

**Comment by XDiamond7D7** [comment]
@MattiaBLX ah, non ci avevo pensato.. Ho preso il vps di Rhosting, quello da 6 euro (High performance)

**Comment by giovanniacanforah** [comment]
@XDiamond7D7 Disdetta e ricompri

**Comment by alsoGAMER** [comment]
> @XDiamond7D7 Apache, nginx, httpd o altro

@V1rusFalcon si mangiano?

**Comment by giovanniacanforah** [comment]
@alsoGAMER Si, sono buoni

**Comment by XDiamond7D7** [comment]
@giovanniacanforah ma perdo i soldi (7 euro perchè ho usato paysafecard)

**Comment by alsoGAMER** [comment]
LOL

**Comment by alsoGAMER** [comment]
> @XDiamond7D7 Ok. Compra un webhost, no?

CAAAAAAANCER

**Comment by giovanniacanforah** [comment]
- @XDiamond7D7 se non sai usare server

**Comment by XDiamond7D7** [comment]
> > @XDiamond7D7 Ok. Compra un webhost, no?
> 
> CAAAAAAANCER

perchè?

**Comment by MattiaBLX** [comment]
@alsoGAMER Per favore. Evitiamo l'off topic.
Se non sbaglio RH Rimborsa.
Purtroppo, se non si è capaci di usare un vps linux e non si sa neanche cosa sia un webserver non ha senso continuare.

**Comment by alsoGAMER** [comment]
> @giovanniacanforah ma perdo i soldi (7 euro perchè ho usato paysafecard)

li perdi cmq, rh non rimborsa

**Comment by MattiaBLX** [comment]
@MattiaBLX In questo caso. La miglior scelta è un webhost.

**Comment by XDiamond7D7** [comment]
Ok grazie ancora

**Comment by giovanniacanforah** [comment]
Prego, arrivederci
