### ISSUE TITLE
Vojo install su :;::::::::: switch

### ISSUE THREAD

**Issue by alsoGAMER** [MattiaBLX/AdvTGBot#8]
skazu ne sos, vojo install su mikrotikke switch ma nn si mette u php

**Comment by Invy55** [comment]
wtf?

**Comment by MattiaBLX** [comment]
@alsoGAMER Caro alsoGamer, informazione gratuita, purtroppo, il nostro supporto non riesce ad aiutarla poichè il suo livello di ritardo è troppo elevato. Per trovare qualcuno in grado di aiutarla abbiamo bisogno che lei compili il modulo per la richiesta della 104.
Buon proseguimento

**Comment by giovanniacanforah** [comment]
Ah ok
